export const darkTheme = {
<<<<<<< HEAD
  mode: 'dard',
  STATUS_BAR_STYLE: 'light-content',
  BACKGROUND_COLOR_PRIMARY: '#273250',
  BACKGROUND_COLOR_SECONDARY: '#384168',
  TEXT_COLOR_PRIMARY: '#FCFDFC',
  TEXT_COLOR_SECONDARY: '#98A3B7',
  TEXT_COLOR_THIRDARY: '#FD9790',
  BORDER_RADIUS: 10
};

export const lightTheme = {
  mode: 'light',
  STATUS_BAR_STYLE: 'dark-content',
  BACKGROUND_COLOR_PRIMARY: '#E9EAEE',
  BACKGROUND_COLOR_SECONDARY: '#F7F7F7',
  TEXT_COLOR_PRIMARY: '#4C576A',
  TEXT_COLOR_SECONDARY: '#B4BDC6',
  TEXT_COLOR_THIRDARY: '#FD9790',
  BORDER_RADIUS: 10
};
=======
    mode: "dard",
    PRIMARY_BACKGROUND_COLOR: "#160C4B",
    PRIMARY_TEXT_COLOR: "#EFE7FE",
    PRIMARY_BUTTON_COLOR_ACTIVE: "#35CBCC",
    PRIMARY_BUTTON_COLOR_DISACTIVE: "#291873",
    PRIMARY_BUTTON_TEXT_COLOR_ACTIVE: "#ffffff",
    PRIMARY_BUTTON_TEXT_COLOR_DISACTIVE: "#4D3B9F",
    PRIMARY_ICON_TEXT_COLOR_ACTIVE: "#377FA7",
    PRIMARY_ICON_TEXT_COLOR_DISACTIVE: "#377FA7",
    STATUS_BAR_STYLE: "light-content",
}

export const lightTheme = {
    mode: "light",
    PRIMARY_BACKGROUND_COLOR: "#F8FAF9",
    PRIMARY_TEXT_COLOR: "#202221",
    PRIMARY_BUTTON_COLOR_ACTIVE: "#5F6ADC",
    PRIMARY_BUTTON_COLOR_DISACTIVE: "#F8F8FF",
    PRIMARY_BUTTON_TEXT_COLOR_ACTIVE: "#ffffff",
    PRIMARY_BUTTON_TEXT_COLOR_DISACTIVE: "#DBDCDF",
    PRIMARY_ICON_TEXT_COLOR_ACTIVE: "#ffffff",
    PRIMARY_ICON_TEXT_COLOR_DISACTIVE: "#C2C1C6",
    STATUS_BAR_STYLE: "default",
}
>>>>>>> feature/quan
