export const darkTheme = {
    mode: "dard",
    PRIMARY_BACKGROUND_COLOR: "#160C4B",
    PRIMARY_TEXT_COLOR: "#EFE7FE",
    PRIMARY_BUTTON_COLOR_ACTIVE: "#35CBCC",
    PRIMARY_BUTTON_COLOR_DISACTIVE: "#291873",
    PRIMARY_BUTTON_TEXT_COLOR_ACTIVE: "#ffffff",
    PRIMARY_BUTTON_TEXT_COLOR_DISACTIVE: "#4D3B9F",
    PRIMARY_ICON_TEXT_COLOR_ACTIVE: "#377FA7",
    PRIMARY_ICON_TEXT_COLOR_DISACTIVE: "#377FA7",
    STATUS_BAR_STYLE: "light-content",
}

export const lightTheme = {
    mode: "light",
    PRIMARY_BACKGROUND_COLOR: "#F8FAF9",
    PRIMARY_TEXT_COLOR: "#202221",
    PRIMARY_BUTTON_COLOR_ACTIVE: "#5F6ADC",
    PRIMARY_BUTTON_COLOR_DISACTIVE: "#F8F8FF",
    PRIMARY_BUTTON_TEXT_COLOR_ACTIVE: "#ffffff",
    PRIMARY_BUTTON_TEXT_COLOR_DISACTIVE: "#DBDCDF",
    PRIMARY_ICON_TEXT_COLOR_ACTIVE: "#ffffff",
    PRIMARY_ICON_TEXT_COLOR_DISACTIVE: "#C2C1C6",
    STATUS_BAR_STYLE: "default",
}